id: PC041002E
initial_creation_type: ocr
source_metadata:
  volumes:
    dde65ea87353464fbace725ef91a882d:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་འཇིག་རྟེན་དབང་ཕྱུག་ཡི་གེ་དྲུག་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
